## Ejercicio 1

In [1]:
import numpy as np

array_1 = np.array([88,23,39,41])

array_2 = np.array([[76.4,21.7,38.4],
                    [41.2,52.8,68.9]])

array_3 = np.array([[12],
                    [4],
                    [9],
                    [8]])

print(array_1, '\n\n', array_2, '\n\n', array_3, '\n\n')

[88 23 39 41] 

 [[76.4 21.7 38.4]
 [41.2 52.8 68.9]] 

 [[12]
 [ 4]
 [ 9]
 [ 8]] 




## Ejercicio 2

In [9]:
M=np.diag(np.arange(50, dtype='int64'))
M,M.ndim,M.size,M.shape,M.dtype

(array([[ 0,  0,  0, ...,  0,  0,  0],
        [ 0,  1,  0, ...,  0,  0,  0],
        [ 0,  0,  2, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ..., 47,  0,  0],
        [ 0,  0,  0, ...,  0, 48,  0],
        [ 0,  0,  0, ...,  0,  0, 49]], dtype=int64),
 2,
 2500,
 (50, 50),
 dtype('int64'))